# Generated by Django 3.0.3 on 2020-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200520_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sw', 'Sport wear'), ('S', 'Shirt'), ('OW', 'Outwear')], max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('P', 'primary'), ('S', 'secondary')], max_length=200),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
