# Generated by Django 3.0.3 on 2020-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200520_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='details',
            field=models.SlugField(default='details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sw', 'Sport wear'), ('OW', 'Outwear'), ('S', 'Shirt')], max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('P', 'primary'), ('S', 'secondary')], max_length=200),
        ),
    ]
